---
title: "01-gene-exp-import"
output: html_document
---


```{r}
library(tidyverse)
```

```{r}
exp <- read.delim("../data/myt-gene-exp.csv", sep = ",")
```

```{r}
exp <- drop_na(exp)
```


```{r}
ggplot(exp, aes(x = Size.L, y = Size.H, color = treatment)) +
  geom_point() +
  geom_smooth(method = "lm")
```


```{r}
exp %>% 
  group_by(treatment) %>%
  summarise(sem = sd(GADD45.converted)/sqrt(n()),
            GADD45.converted = mean(GADD45.converted)) %>%
  ggplot(aes(x = treatment, y = GADD45.converted)) + 
  geom_col(position = "dodge",
           width = 0.4) + 
  geom_errorbar(aes(ymin=GADD45.converted-sem, ymax=GADD45.converted+sem), width=.4,
                position = position_dodge()) +
  labs(x ="", y = "GADD45 expression", legend.title="") 
```


```{r}
exp %>% 
  group_by(treatment) %>%
  summarise(sem = sd(sHSP24.converted)/sqrt(n()),
            sHSP24.converted = mean(sHSP24.converted)) %>%
  ggplot(aes(x = treatment, y = sHSP24.converted)) + 
  geom_col(position = "dodge",
           width = 0.4) + 
  geom_errorbar(aes(ymin=sHSP24.converted-sem, ymax=sHSP24.converted+sem), width=.4,
                position = position_dodge()) +
  labs(x ="", y = "sHSP24 expression", legend.title="") 
```
```{r}
exp %>% 
  ggplot(aes(x = treatment, y = HSP90.converted)) + 
  geom_boxplot() + 
  geom_jitter(shape=16, position=position_jitter(0.2)) +
  labs(x ="", y = "hsp90 expression", legend.title="") 
```
```{r}
exp %>% 
  ggplot(aes(x = treatment, y = sHSP24.converted)) + 
  geom_violin() + 
  labs(x ="", y = "sHSP24 expression", legend.title="") 
```
```{r}
write_delim(exp, "../output/expression_01.tab", delim = "\t")
```



```{r}
exp_long <- read.delim("../data/exp_longer.txt", sep = "\t")
```


```{r log-transform-exp}
exp_long <- exp_long %>%
  mutate(gene_norm = log10(exp))
```


```{r}
exp_long %>% 
  ggplot(aes(x = treatment, y = gene_norm, fill = treatment)) + 
  geom_boxplot() + 
  geom_jitter(shape=1, position=position_jitter(0.2)) +
  facet_grid(~gene) +
  scale_fill_manual(values=c("#bbeeee", "#ffa500")) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(),
                      axis.ticks.x=element_blank()) +
  ylab("gene expression (log10 arbitrary)")
```

```{r write-boxplots-to-file}

# Specify SVG image name/location.
svg("../figures/log10-exp-boxplots.svg")

exp_long %>% 
  ggplot(aes(x = treatment, y = gene_norm, fill = treatment)) + 
  geom_boxplot() + 
  geom_jitter(shape=1, position=position_jitter(0.2)) +
  facet_grid(~gene) +
  scale_fill_manual(values=c("#bbeeee", "#ffa500")) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(),
                      axis.ticks.x=element_blank()) +
  ylab("gene expression (log10 arbitrary)")

# Close image device
dev.off()

```




```{r}
exp_long %>% 
  ggplot(aes(x = treatment, y = exp)) + 
  geom_boxplot() + 
  geom_jitter(shape=1, position=position_jitter(0.1)) +
  facet_grid(~gene)
```




```{r}
t.test(exp$GADD45.converted~exp$treatment)
```
```{r}
t.test(exp$sHSP24.converted~exp$treatment)
```



```{r}
t.test(exp$HSC70.converted~exp$treatment)
```
```{r}
summary(glm(exp$HSC70.converted~exp$treatment))

```

